def test_all_imports():
    import src.presentation.di_container
    import src.presentation.app
    import src.presentation.theme_manager
    import src.presentation.viewmodels.playlists_viewmodel
    import src.presentation.viewmodels.downloads_viewmodel
    import src.presentation.viewmodels.library_viewmodel
    import src.presentation.viewmodels.search_viewmodel
    import src.presentation.viewmodels.settings_viewmodel
    import src.presentation.widgets.track_card
    import src.presentation.widgets.custom_progress
    import src.presentation.tabs.search_tab
    import src.presentation.tabs.settings_tab
    import src.presentation.tabs.playlists_tab
    import src.presentation.tabs.library_tab
    import src.presentation.tabs.downloads_tab
    import src.infrastructure.downloader
    import src.infrastructure.http.http_client
    import src.infrastructure.metadata.cover_downloader
    import src.infrastructure.metadata.processor
    import src.infrastructure.database.db
    import src.infrastructure.database.models
    import src.infrastructure.database.repositories.track_repository
    import src.infrastructure.database.repositories.playlist_repository
    import src.infrastructure.database.repositories.playlist_track_repository
    import src.infrastructure.sources.archive_parser
    import src.infrastructure.sources.pixabay_parser
    import src.infrastructure.sources.bensound_parser
    import src.infrastructure.sources.fma_parser
    import src.infrastructure.sources.jamendo_parser
    import src.infrastructure.sources.base_parser
    import src.infrastructure.sources.soundclick_parser
    import src.domain.constants
    import src.domain.entities
    import src.domain.events
    import src.domain.interfaces
    import src.domain.exceptions
    import src.shared.utils
    import src.shared.validators
    import src.database.repository
    import src.database.db
    import src.database.models
    import src.application.event_bus
    import src.application.services.search_service
    import src.application.services.settings_service
    import src.application.services.library_service
    import src.application.services.parser_manager
    import src.application.services.playlist_service
    import src.application.services.metadata_service
    import src.application.services.download_service
    import src.sources.archive_parser
    import src.sources.pixabay_parser
    import src.sources.bensound_parser
    import src.sources.fma_parser
    import src.sources.jamendo_parser
    import src.sources.base_parser
    import src.sources.soundclick_parser
